"""Agents submodule."""

from synto.agents.base import BaseAgent, AgentResult
from synto.agents.workflow_agents import (
    DiscoveryAgent,
    PlannerAgent,
    ImplementerAgent,
    TesterAgent,
    QAGateAgent,
    create_agents,
)
from synto.agents.all_agents import (
    HermesOrchestrator,
    CodeOrchestrator,
    BusinessAnalyst,
    ProductManager,
    Planner,
    CodebaseExplorer,
    Architect,
    SystemDesigner,
    Tester,
    BackendImplementer,
    FrontendImplementer,
    ContractAligner,
    Reviewer,
    SecurityReviewer,
    QAGatekeeper,
    DependencyChecker,
    TechnicalWriter,
    ReleaseManager,
    Builder,
    create_all_agents,
)

__all__ = [
    "BaseAgent",
    "AgentResult",
    "DiscoveryAgent",
    "PlannerAgent",
    "ImplementerAgent",
    "TesterAgent",
    "QAGateAgent",
    "create_agents",
    "HermesOrchestrator",
    "CodeOrchestrator",
    "BusinessAnalyst",
    "ProductManager",
    "Planner",
    "CodebaseExplorer",
    "Architect",
    "SystemDesigner",
    "Tester",
    "BackendImplementer",
    "FrontendImplementer",
    "ContractAligner",
    "Reviewer",
    "SecurityReviewer",
    "QAGatekeeper",
    "DependencyChecker",
    "TechnicalWriter",
    "ReleaseManager",
    "Builder",
    "create_all_agents",
]
